name: 'Test'

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  run:
    environment: development
    env: 
      TEST_ENV: ${{ secrets.TEST }}
    runs-on: ubuntu-latest

    steps:
      - name: TEST
        run:  | 
          echo "ENV: $(echo '${{ secrets.TEST }}' | base64)"
      - name: Set repository secret TEST
        uses: mmercan/actions-set-secret@v/4.0.0
        with:
          name: 'TEST_SECRET'
          value: "WDWD"
          token: ${{ secrets.REPO_TOKEN }}
          environment: development
      - name: create env var
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            github.rest.actions.createEnvironmentVariable({
              ${{ github.repository_id }},
              development,
              TEST2,
              TEST2,
            });
