name: 'Test'

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  run:
    environment: development
    env: 
      TEST_ENV: ${{ secrets.TEST_SECRET }}
    runs-on: ubuntu-latest

    steps:
      - name: TEST
        run:  | 
          echo "ENV: $(echo '${{ secrets.TEST_SECRET }}' | base64)"
          echo "ENV: $(echo '${{ secrets.TEST_SECRET2 }}' | base64)"
          echo "ENV: $(echo '${{ secrets.TEST_SECRET_GH }}' | base64)"
      - run: gh secret set TEST_SECRET_GH -e development --body value
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      - name: Set repository secret TEST
        uses: mmercan/actions-set-secret@v/4.0.0
        with:
          name: 'TEST_SECRET'
          value: "WDWD"
          token: ${{ secrets.REPO_TOKEN }}
          environment: development
      - name: create env var
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            github.rest.actions.createEnvironmentVariable({
              ${{ github.repository_id }},
              development,
              TEST2,
              TEST2,
            });
