name: 'Test'

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  run:
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: create env var
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            github.rest.actions.createEnvironmentVariable({
              repository_id: ${{ github.repository_id }},
              environment_name: 'development',
              name: 'TEST2',
              value: 'TEST2',
            });