name: 'Test'

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  run:
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: update env var
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repositories/${{ github.repository_id }}/environments/development/variables \
          -d '{"name":"TEST","value":"TEST"}'